name: CD Pipeline - Prod

on:
  push:
    branches: [prod]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx:alpine3.23
          format: table
          exit-code: 0

  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove old container
        shell: powershell
        run: |
          $container = docker ps -q --filter "name=intranet-newdeal"
          if ($container) {
            docker stop intranet-newdeal
            docker rm intranet-newdeal
          }

      - name: Pull image
        shell: powershell
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev

      - name: Run container
        shell: powershell
        run: |
          docker run -d --name intranet-newdeal -p 80:80 `
